### ISSUE TITLE
Symbol lookup for reflection

### ISSUE THREAD

**Issue by tsloughter** [tomas-abrahamsson/gpb#163] opened 2019-01-23 15:50 UTC
I think there are just 2 issues here and 1 of those I have an ok work around for.

The first is that there isn't an unmodified version of names that are transformed, like to snake case. I figure the work around for this is to just check possible modifications of each requires symbol as well. So if not found in the first iteration of possible matches, convert to snake case and try again. This will likely work fine.

Second is that gpb puts all imported protos into the one module. So if I have `test.proto` that imports `messages.proto` there is no way to tell that when comparing a symbol to what is in `test_pb.erl` whether that symbol was actually in `test.proto` or if it is the result of importing `messages.proto`. Thus the file descriptor for `test.proto` might be returned when the one for `messages.proto` is what was really wanted.

Any idea on how to solve the second issue? Maybe that information is already in the generate module somewhere and I'm just missing it?

**Comment by tomas-abrahamsson** [comment] 2019-01-23 18:46
Hmm, yes, for the second issue, you are right in that the generated module does not contain enough information to recreate descriptors on a per-proto basis. To some extent the internal format could help, but not all the way. It contains for instance `{{msg_containment,"test"},[MsgName1,...]}` for `"test.proto"` and so on for other .proto files. Besides `msg_containment`, there is also `service_containment` and `rpc_containment` but nothing for instance for enums. This information exists during parsing and code generation, but the containment information is lost in the generated `get_msg_defs/0` function, which contains just, well, message definitions. If this containment info was extended to cover more, then in theory, it ought to be possible to use it to split definitions per proto. Aside for enums, it would have to be extended to cover `extends`, `options`, `reserved` and probably more, so it would be a bit of work.

Another approach could also be to rethink the approach to put all imported protos in one module.

I'll have to ponder it a bit.

**Comment by tsloughter** [comment] 2019-01-24 16:16
Hm, so maybe I should have the grpcbox plugin build a reflection module with the necessary info from the internal format gpb uses? That sounds doable. And I don't think it has to be extended to cover anymore than just enums, at least for reflection support.

I think being able to have the generated modules call each other instead of having everything in one module would be nice, but not necessary.

**Comment by tomas-abrahamsson** [comment] 2019-01-26 11:16
I pushed some experimental code to a branch, more-introspects, to see if it is anything you could have use for. It generates these functions:

* enum_name_to_fqbin/1 and msg_name_to_fqbin/1, fqbin_to_enum_name/1 and fqbin_to_msg_name/1 (the msg_name functions take any renaming and package options inyo consideration) 
* get_msg_containment/1, get_enum_containment/1, get_pkg_containment/q, get_service_containment/1 and get_rpc_containment/1
* get_all_proto_names/0

The get_all_proto_names will return all proto filenames sans extensions in top-down import order. The first one is always the "main" proto file. These proto names can be used as input to the various get_xyz_containment/1 functions. Translation to fully qualified format (ie with package name prepended as necessary) can be done with the xyz_name_to_fqbin/1 functions, and searching could be done using the inverse functions.

I hope these functions could be useful, any thoughts are of course welcome.

**Comment by tomas-abrahamsson** [comment] 2019-01-26 15:35
Right, I had forgotten about the neef for descriptors per proto. Is your plan to compile the main proto and then each imported proto once morr to get its descriptor? (I can't think of any other good way to do it at the moment, unfortunately)

Your walk-through made me realize there could be a need for going from fqbin to proto name. It wouldn't be difficult as the info is there, but I'm not able to do it during the weekend. Maybe it could go as an optimization/simplification latet on.

**Comment by tomas-abrahamsson** [comment] 2019-01-31 07:11
I (force-)pushed  to the more-introspects branch, adding some functions for reverse-lookup:

* get_proto_by_msg_name_as_fqbin/1
* get_proto_by_service_name_as_fqbin/1
* get_proto_by_enum_name_as_fqbin/1
* get_protos_by_pkg_name_as_fqbin/1

I'll see if I can take a stab at descriptors per proto next. (I think there could be a way to avoid the need for compiling each proto on its own by slightly extending the internal format.)

**Comment by tsloughter** [comment] 2019-02-02 16:52
This is great! I also realized that the `msg_name_to_fqbin` solves another issue I had just ignored at the time, the grpc headers are supposed to include `grpc-message-type` with the fully qualifed input message name, now I can easily throw that in the generated client modules.

**Comment by tomas-abrahamsson** [comment] 2019-02-05 21:14
Nice! I just pushed again to the `more-introspects` branch (not a force-push this time). This time, I added generation of `descriptor/1` for retrieving descriptors per proto. The argument is the proto filename (base name sans extension)

The `descriptor/0` is still available and as previously, it still returns a descriptor for all the protos. (I don't think it matters much, but I slightly modified the encoding to descriptor for `descriptor/0`: The file descriptor structure contains a list of files. Previously, it reported a descriptor containing only one file entry, even when there were several imported files. To be able to provide descriptor per proto, I added entries to the intermediate format to be able to track what file each entry belongs to. This also made it possible for `descriptor/0` to return a more proper list of file entries, one list item for each imported file.)

**Comment by tsloughter** [comment] 2019-02-06 15:56
@tomas-abrahamsson awesome, this works and covers everything I need.

The only thing is I haven't been able to get reflection to actually work with a third party. Trying a client named polygot right now and will try others, but despite returning the file descriptor it complains it isn't able to find the service in that file descriptor.

Do you think there be an issue with what other clients expect of a file descriptor and what gpb generates?

Though I'm also confused why the response is a repeated bytes field instead of just bytes. I'm simply wrapping the `descriptor/1` response in a list:

```
            {file_descriptor_response,
             #{file_descriptor_proto => [M:descriptor(P)]}}
```

**Comment by tomas-abrahamsson** [comment] 2019-02-06 20:08
> despite returning the file descriptor it complains it isn't able to find the service in that file descriptor

Hmm... Difficult to know why. Maybe there's something wrong with packages, I can try to cross-check with what protoc computes. It seems with the `use_packages` option, the service name gets a package, but the rpc name does not. I will try to look into it.

**Comment by tomas-abrahamsson** [comment] 2019-02-06 22:43
Could you try the `fix-descriptor` branch? (it builds on top of `more-introspects`). It is an attempt. It encodes the `descriptor/0` as a `ProtoDescriptorProto` message, this seems to be what the protoc does. Previously, it was a `ProtoDescriptorSet` message, which contains just a `repeated ProtoDescriptorProto file` field.

I'm unsure if I also need to fix the service name and message names. In the protoc generated descriptor it is without package name, which I found contrary to intuition, and message names seems to be rooted (ie starting with leading dot). I think I'll try to fix those discrepancies as well in another commit on top, but that might be tomorrow hopefully.

**Comment by tomas-abrahamsson** [comment] 2019-02-06 22:58
Pushed again

**Comment by tsloughter** [comment] 2019-02-07 00:14
It seems to be getting closer, now erroring that it can't find `point`, so the error is after it is able to find the service in the descriptor:

```
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Using proto descriptors fetched by reflection
[main] WARN me.dinowernli.grpc.polyglot.protobuf.ServiceResolver - Skipped descriptor route_guide.proto due to error
com.google.protobuf.Descriptors$DescriptorValidationException: routeguide.RouteGuide.GetFeature: ".point" is not defined.
```

**Comment by tomas-abrahamsson** [comment] 2019-02-08 12:51
I see. Thanks for testing it out. I'll try to look into it next week.

**Comment by tsloughter** [comment] 2019-02-08 15:01
Great, thanks for looking into all this!

**Comment by tomas-abrahamsson** [comment] 2019-02-17 19:13
I've (force-)pushed to the `fix-descriptor` branch again, and have tried to do it a bit more thoroughly this time, cross-checking with protoc seems to be producing. There may still be issues, but I hope it will work better.

(had to do a small update to the last commit of the `more-introspect` branch too, from which `fix-descriptor` spins off)

**Comment by tsloughter** [comment] 2019-02-22 16:28
Great, I'm trying now!

**Comment by tsloughter** [comment] 2019-02-22 17:08
Still failing :(. I tried with multiple grpc cli clients. The error given by `evans` is:

```
* 1: failed to initialize: failed to list services by gRPC reflection: File "health.proto" included an unresolvable reference to ".grpc.health.v1.HealthCheckResponse.ServingStatus"
```

This is the result after it successfully retrieves the file descriptor for the health service.

**Comment by tomas-abrahamsson** [comment] 2019-02-22 18:12
Oh, I see, sorry. I think I ought to test the whole chain with grpc reflection for some representative proto files. Would it be posssible to describe something to do that?

**Comment by tsloughter** [comment] 2019-02-26 19:04
Yea, what I do is checkout the `full-reflection` branch of https://github.com/tsloughter/grpcbox and then add `gpb` as a checkout:

```
ln -s /path/to/your/gpb _checkouts/gpb
rebar3 grpc gen
rebar3 as test shell
```

This will regenerate the proto modules with gpb and start the reflection server.

Then run `evans` https://github.com/ktr0731/evans with `-r` for reflection and 8080 for the port and pass in the `proto/*` directory that is in the checkout of `grpcbox` at the top level.

```
evans -p 8080 -r proto/*
1 error occurred:
	* 1: failed to initialize: failed to list packages by gRPC reflection: File "health.proto" included an unresolvable reference to ".grpc.health.v1.HealthCheckResponse.ServingStatus"
```

**Comment by tomas-abrahamsson** [comment] 2019-02-26 20:43
Thanks for instructions!

**Comment by tomas-abrahamsson** [comment] 2019-03-08 07:32
I pushed again to the `fix-descriptor` branch. I managed to run `evans` in reflection mode, and make some rpc calls to both `Health` and `routeguide`. Thanks again for good instructions to reproduce!

The major error that is now fixed, is that the generated descriptor info was based on the protobuf definitions _after_ renaming operations, but I think the only sensible thing is to base it on the original defintions before any renaming operations, so that upper/lower case, underscores etc in all names match what is in the `.proto` file.

**Comment by tsloughter** [comment] 2019-03-08 15:15
Ah! Makes sense. And works! Thanks again, this is really great.

**Comment by tsloughter** [comment] 2019-03-08 15:24
Just found one possible issue though, enums in the generated module have the wrong name. For `health.proto` I get:

```
get_proto_by_enum_name_as_fqbin(<<"health_check_response.ServingStatus">>) -> "health";
get_proto_by_enum_name_as_fqbin(E) ->
    error({gpb_error, {badenum, E}}).
```

But I think it should be `grpc.health.v1.HealthCheckResponse.ServingStatus`.

**Comment by tomas-abrahamsson** [comment] 2019-03-08 18:37
Oops, you're absolutely right! Fixed it (also added a test case) and (force-)pushed the `fix-descriptor` branch again. (Amended the 3rd last commit). Hope this will do it!

**Comment by tsloughter** [comment] 2019-03-08 18:44
Woo, yup, my tests pass now :)

**Comment by tomas-abrahamsson** [comment] 2019-03-08 18:47
Super! I'll merge it to master shortly then.

**Comment by tomas-abrahamsson** [comment] 2019-03-08 20:30
Got a bit distracted for a while, but just wanted to say that I pushed 4.7.0 including the latest version of the fix-descriptor branch.

However, maybe useful to know, is that there seems to be some build issue, see lrascao/rebar3_gpb_plugin#90 don't yet know how this will impact. (This 4.7.0 compiles an eunit test—`gpb_compile_descr_tests`—as a compile post_hook, which is a bit unusual, the build process for descriptors is a bit complicated, and I could not find any better way to do it; it depends on gpb_compile_descr, which depends on the base gpb to have been compiled)

**Comment by tsloughter** [comment] 2019-03-08 20:39
It may be because `test` dir isn't included in the hex package.

**Comment by tomas-abrahamsson** [comment] 2019-03-08 21:17
Yes, that's it. Will update the descriptor compilation helper script to accommodate.

**Comment by tomas-abrahamsson** [comment] 2019-03-08 23:15
I hope I got descriptor compilation right in 4.7.1, so I'll be closing this ticket now. Thanks for all valuable feedback and patience!

**Closed by tomas-abrahamsson** 2019-03-08 23:15 UTC
