### ISSUE TITLE
dialyzer warnings for required messages

### ISSUE THREAD

**Issue by GeraldXv** [tomas-abrahamsson/gpb#128] opened 2018-01-19 06:18 UTC
common.proto
     message name_card {...}
game.proto
     message user{... 
                            required name_card name_card = 10
                           ...}.
the dialyzer will through game_pb.erl a warning 
   Guard test ...== 'undefined' can never succeed.
please help.

**Comment by tomas-abrahamsson** [comment] 2018-01-19 08:11
What options do you use for gpb and for dialyzer?

**Comment by GeraldXv** [comment] 2018-01-20 02:18
Attached GPB OPTS:
{gpb_opts, [
    {i, "proto"},
    {module_name_suffix, "_pb"},
    {o_erl, "src/_erl"},
    {o_hrl, "include"},
    defaults_for_omitted_optionals
]}.
Dialyzer:
As I am using rebar3, I just ran rebar3 dialyzer in my project.
Detailed warnings:
_build/default/lib/game_svr/src/_erl/game_pb.erl
3082: Guard test PFname_card::#name_card{name::maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | byte(),binary() | []),icon::maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | byte(),binary() | [])} == 'undefined' can never succeed

**Comment by tomas-abrahamsson** [comment] 2018-01-22 19:43
It seem to be a regression that has sneaked into the 4.x.x. I'll look into fixing it.

(I've previously only executed dialyzer tests manually from time to time on the generated code, mainly due to the time it takes to run, for a lot of different fields, types and gpb options, so it has slipped through. But recently, I've seen improvements in dialyzer, almost making it feasible to run more regularly)

**Comment by tomas-abrahamsson** [comment] 2018-01-24 20:49
I just pushed a couple of fixes to a branch, `fix-dialyzer-issues`. Would you like to try it out? Hopefully things should dialyze better.

**Comment by GeraldXv** [comment] 2018-01-25 02:03
Cool. The fix-dialyzer-issues works. Now the dialyzer logs are much better to read. Thanks a lot.
Really looking forward to the next release.

**Comment by tomas-abrahamsson** [comment] 2018-01-26 08:08
I just pushed 4.1.2, which includes the fix. I'm closing the issue, just re-open if there's anything more about it.

**Closed by tomas-abrahamsson** 2018-01-26 08:08 UTC
