### ISSUE TITLE
map<string,string> not generating proper erlang

### ISSUE THREAD

**Issue by TooPro** [tomas-abrahamsson/gpb#171] opened 2019-10-04 19:02 UTC
I noticed that if I use a protobuf type map<string,string> in my .proto, the code that is generated by the file gets multiple warning from dialyzer. If I comment the line and recompile, everything works perfectly no warnings. 

here is an exemple of the message in my .proto file.

message Log {
  LogLevel level = 1; 
  string event = 2;
  string function = 3;
  string file_name = 4;
  uint32 line = 5;
  string msg = 6;
  map<string,string> extra = 7;
}

here is some of the errors:

7531: Function from_json_msg_Log/2 has no local return
7533: Record construction #'Log'{extra::dict:dict(_,_)} violates the declared type of field extra::'undefined' | [{binary() | maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | byte(),binary() | []),binary() | maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | byte(),binary() | [])}]

7542: Function fj_msg_Log/3 will never be called
7656: Function fj_mapfield_fold/8 will never be called
7663: Function fj_mapfield_fold_aux/7 will never be called

Am I doing something wrong or is this a bug?

**Comment by tomas-abrahamsson** [comment] 2019-10-04 20:13
This looks like a bug. I'll take a look. What json option do you use?

**Comment by TooPro** [comment] 2019-10-04 20:15
{gpb_opts,
  [
    json,
    {json_format, maps},
    {json_key_format, binary},
    {json_object_format, map},
    {json_string_format, binary}
  ]
}.

**Comment by tomas-abrahamsson** [comment] 2019-10-04 21:35
Confirmed. However, I'll have to think a bit on how to solve it.

**Comment by tomas-abrahamsson** [comment] 2019-10-05 11:22
I believe the dialyzer issue is fixed in the just-pushed 4.10.4, so I'll be closing this issue. Feel free to just reopen or open a new if there's anything more.

**Closed** 2019-10-05 11:22 UTC
