### ISSUE TITLE
Spec. for empty message

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [tomas-abrahamsson/gpb#196] opened 2021-02-07 02:20 UTC
`gpb` is able to generate code for a message declared as

```
message MyMessage {
}
```

but then `-spec(_).`s this as 

```
-spec encode_msg('...MyMessage'(), atom()) -> binary().
```

`dialyzer` is picky (but also right) and states that the return type is too generic, since it could be just `<<>>`.

Do you think it's reasonable to accept its suggestion and generate a stricter `-spec(_).`?

**Note**: I understand that an empty message is meaningless (though we're using it in an example for later extensibility), but since `gpb` generates the code... 😄

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-07 02:38
Hm... I forgot to mention I'm using `dialyzer` option `underspecs`: "Warn about underspecified functions (the specification is strictly more allowing than the success typing)."

**Comment by tomas-abrahamsson** [comment] 2021-02-07 13:49
I'll look into restricting the spec a bit. Thanks for mentioning `underspecs`.

Have you seen this for more than encode_msg?

(Dialyzer's strictness makes for more work for code generator writers :) )

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-07 14:12
> Have you seen this for more than encode_msg?

Not yet, no. But I guess it might happen for `decode_msg` to.

At the same time, with a single message, the `atom()` bit of the `-spec(_).` also gets a warning (it goes away after 13 messages are declared[1]).

> Dialyzer's strictness makes for more work for code generator writers :)

Yeah, I understand. My workaround, for the moment, is to remove `underspecs`, but it's very useful, in order to not have people write stuff like `-spec all(any()) -> any().`

---

[1] https://github.com/erlang/otp/blob/master/lib/dialyzer/src/erl_types.erl#L250: it seems, at a certain moment in time, somebody decided that `-spec(_).`ing more than 13 different "something"s was not acceptable anymore (I agree with the principle, not the number in specific, since it's arbitrary, it seems), after which a more generic type is OK 😄.

i.e. for

```erlang
-spec stop(pos_integer()) -> ok.
stop(1) -> ok;
stop(2) -> ok;
stop(3) -> ok;
stop(4) -> ok;
stop(5) -> ok;
stop(6) -> ok;
stop(7) -> ok;
stop(8) -> ok;
stop(9) -> ok;
stop(10) -> ok;
stop(11) -> ok;
stop(12) -> ok;
stop(13) -> ok;
stop(14) -> ok.
```

you get `a supertype of the success typing: mylib_app:stop(1..255) -> 'ok'`, while for

```erlang
-spec stop(pos_integer()) -> ok.
stop(1) -> ok;
stop(2) -> ok;
stop(3) -> ok;
stop(4) -> ok;
stop(5) -> ok;
stop(6) -> ok;
stop(7) -> ok;
stop(8) -> ok;
stop(9) -> ok;
stop(10) -> ok;
stop(11) -> ok;
stop(12) -> ok;
stop(13) -> ok.
```

you get `a supertype of the success typing: mylib_app:stop(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13) -> 'ok'`.

At the same time

```erlang
-spec stop(atom()) -> ok.
stop(a) -> ok;
stop(b) -> ok;
stop(c) -> ok;
stop(d) -> ok;
stop(e) -> ok;
stop(f) -> ok;
stop(g) -> ok;
stop(h) -> ok;
stop(i) -> ok;
stop(j) -> ok;
stop(k) -> ok;
stop(l) -> ok;
stop(m) -> ok;
stop(n) -> ok.
```

shows no warnings, whereas

```erlang
stop(a) -> ok;
stop(b) -> ok;
stop(c) -> ok;
stop(d) -> ok;
stop(e) -> ok;
stop(f) -> ok;
stop(g) -> ok;
stop(h) -> ok;
stop(i) -> ok;
stop(j) -> ok;
stop(k) -> ok;
stop(l) -> ok;
stop(m) -> ok;
stop(n) -> ok.
```

does. Fun stuff!

**Comment by tomas-abrahamsson** [comment] 2021-02-07 15:01
I've pushed `<<>>` instead of `binary()` for the return type to a (temporary) branch, `fix-specs-for-empty-msg` in case you'd like to try it out.

> At the same time, with a single message, the atom() bit of the -spec(_). also gets a warning (it goes away after 13 messages are declared[1]).

Hmm, I see. (I read this after I had pushed to the temporary branch.) How best to handle this? The obvious way would be to always generate a union of message names, but I'm thinking it would also make the spec a bit less readable to humans.

**Comment by tomas-abrahamsson** [comment] 2021-02-07 15:13
> more than 13 different "something"s

Interesting findings! :) It seems ranges of integers are handled differently from sets of other type of elements, some things are more equal than others. Otherwise, I'd have thought 17 would be a more generic number as per the [Jargon file](http://www.catb.org/~esr/jargon/html/R/random-numbers.html) :)

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-07 15:20
> 17 would be a more generic number as per the Jargon file :)

I was unaware of this 😄; fun stuff.

> always generate a union of message names

I agree it's less than ideal, and it's actually the first time I've see it. Let me see if this is something new or how I was avoiding this before (I'm usually strict with the static analysis).

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-07 15:55
Your change did what you set out to do, but it didn't fix it all:
```erlang
is a supertype of the success typing: ..._pb:encode_msg(#{},'...MyMessage') -> <<>>
```

Possible workarounds:
* remove `underspecs` from the analysis,
* remove `type_specs` from `gpb_opts`,
* add a `-dialyzer` directive to the functions (though `no_underspecs` does not exist, and `nowarn_function` is too generic),
* have more than 13 messages 😄,
* ...

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-07 16:04
I've [opened a New feature discussion](https://bugs.erlang.org/browse/ERL-1480), in https://bugs.erlang.org/, to check if `no_underspecs` is something that could be added to Erlang/OTP, but that's a future solution, of course.

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-07 16:11
In any case, you're already enumerating all the possible message maps in one of the argument's `-spec(_).`...

**Comment by tomas-abrahamsson** [comment] 2021-02-07 16:37
I'll take a closer look. It might be possible to get something reasonably readable with some more types, maybe something like `-type message_name() :: msg1 | msg2 | ...` and then use `message_name()` instead of `atom()`

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-07 17:13
> I'll take a closer look. It might be possible to get something reasonably readable with some more types, maybe something like `-type message_name() :: msg1 | msg2 | ...` and then use `message_name()` instead of `atom()`

I'd thought about suggesting something of this sort. And if you do reach it, probably doing the same for the message map would increase readability.

Otherwise, it's also possible (better?) to have spec domains, like.

```erlang
-spec encode_msg
        (MessageA, NameA) -> EncodedA;
        (MessageB, NameB) -> EncodedB;
        (MessageC, NameC) -> EncodedC;
...
```

and this further improves the static analysis, since you can't have `MessageA` with `NameB`, which you will otherwise.

**Comment by tomas-abrahamsson** [comment] 2021-02-08 20:55
> In any case, you're already enumerating all the possible message maps in one of the argument's `-spec(_).`...
> [...]
> Otherwise, it's also possible (better?) to have spec domains

True, and good idea! I'll meditate and experiment a bit.

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-09 00:04
🧘

**Comment by tomas-abrahamsson** [comment] 2021-02-11 20:38
I have now (force-)pushed to the branch, `fix-specs-for-empty-msg`, fixing I hope both the `atom()` for message names, and the empty binary. I ended up introducing some types to make the generated code more readable.

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-11 21:58
I'll test it. Hang tight.

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-11 22:38
Tested it!

`dialyzer`-wise it seems perfect: there's no more warnings (tested up to OTP 24).

This is what I'm getting
```erlang
-spec encode_msg('$msg'(), '$msg_name'()) -> <<>>.
```
(which I think is what you aimed for)

Regarding the generated interface:
```erlang
-export_type(['Message'/0]).
-type '$msg_name'() :: 'Message'.
-type '$msg'() :: 'Message'().
-export_type(['$msg_name'/0, '$msg'/0]).
```
you "seem" to be exporting the map definition twice (in my previous example `'Message'/0`, for a single message, and `'$msg'/0` for a set of all the messages, which I guess is OK if you assume the consumer will be wrapping around the `encode_msg/2` fun (no biggie, here).

Thanks for this, @tomas-abrahamsson.

**Comment by tomas-abrahamsson** [comment] 2021-02-11 22:45
Yes, exactly, when there are more than one message, the `'$msg()'` will be `-type '$msg'() :: 'Message1'() | 'Message2'() | ...` and similarly for `'$msg_name'`. Initially, they would be needed for `-spec`s in the generated code, but I would assume they could be useful also in other scenarios, so they could as well be exported.

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-11 22:51
I'm OK with closing this, if you are. Original issue is more solved than I expected 😄.

**Comment by paulo-ferraz-oliveira** [comment] 2021-02-16 14:29
@tomas-abrahamsson, this might be of help, in future version, to be specific about which warnings to turn off: https://github.com/erlang/otp/pull/4517.

**Comment by tomas-abrahamsson** [comment] 2021-02-27 14:15
Hi again, this is now included in 4.16.2, which was just released. (along with a `-dialyzer({no_underspecs, fn/arity}).` for good measure, if Erlang ≥ 24)

**Comment by paulo-ferraz-oliveira** [comment] 2021-03-01 12:59
Cool. Thanks much.

**Comment by paulo-ferraz-oliveira** [comment] 2021-05-15 10:46
Hi, @tomas-abrahamsson.

I'm getting the following generated code, on `rebar3_hex`.

```
-type 'Signed'() ::
      #{%% payload              => iodata()         % = 1, required
        %% signature            => iodata()         % = 2, optional
       }.
```

`dialyzer` then complains that I'm passing a map which is not correct (to the `encode_msg` fun). `'Signed()`', as-is, means "empty map", here, right? How can I get rid of those `%%` before the key definitions? I tried a couple of options (using the `rebar3_gpb_plugin` but can't seem to get it working).

Thanks for your help.

**Comment by tomas-abrahamsson** [comment] 2021-05-15 11:07
Are you targetting Erlang 17, as well as running an Erlang 17 dialyzer?

> `'Signed()'`, as-is, means "empty map", here, right?

Depends on Erlang version: with Erlang 17, it means "any map", while with Erlang 18 and later (if I remember right) it means an empty map.

**Comment by tomas-abrahamsson** [comment] 2021-05-15 13:35
I tried to find what exactly the `=>` in a map type spec means in Erlang 17 and 18, whether it indicates the association is mandatory or optionally present. In Erlang 19 and later as per that pr, the erlang/otp#1014, it indicates 'optional'. But after some searching and testing, for Erlang 17 and 18, I'm, not so sure.

I found this sentence in the type spec ref doc for both Erlang [17](https://erlang.org/documentation/doc-6.4/doc/reference_manual/typespec.html) and [18](https://erlang.org/documentation/doc-7.3/doc/reference_manual/typespec.html): "No type information of maps pairs, only the containing map types, are used by Dialyzer [...]"

```
$ cat /tmp/m.erl
-module(m).
-export([m/0]).

m() -> m2(#{}).

-spec m2(#{a => integer()}) -> map().
m2(Map) ->
    Map.
$ /usr/local/erlang-18.3.4.9/bin/erlc +debug_info -o /tmp /tmp/m.erl
$ /usr/local/erlang-18.3.4.9/bin/dialyzer -Wunderspecs --plt /.../.plt-18.3.4.9.plt /tmp/m.beam 
  Checking whether the PLT /.../.plt-18.3.4.9.plt is up-to-date... yes
  Proceeding with analysis... done in 0m1.15s
done (passed successfully)
```

Up till now, I had assumed the `=>` in Erlang 17,18 indicated mandatory presence, ie the same as `:=` in Erlang 19, but it seems I have yet to find some definition of what `=>` was intended to indicate in Erlang 17 and 18...

**Comment by tomas-abrahamsson** [comment] 2021-05-15 14:29
> it seems I have yet to find some definition of what => was intended to indicate in Erlang 17 and 18...

Hmm. it seems `=>` in Erlang 17 and 18 indicated optional presence, just like in Erlang 19+, and I had gotten it wrong. References:
* [The type spec section of the eep 43](https://github.com/erlang/eep/blob/master/eeps/eep-0043.md#dialyzer-and-type-specification)
* [A discussion on teh erlang-questions mailing list](https://erlang.org/pipermail/erlang-questions/2016-April/088790.html) and a [gist](https://gist.github.com/kostis/eaf4a06e643cf49314ba) that lays it out in no uncertain terms.

So I guess this means I should revisit type generation in gpb when targeting Erlang 17 and 18. I'll reopen this.

**Comment by paulo-ferraz-oliveira** [comment] 2021-05-17 09:40
Thanks for the analysis and your time.

**Comment by tomas-abrahamsson** [comment] 2021-05-19 18:39
> Hmm. it seems `=>` in Erlang 17 and 18 indicated optional presence, just like in Erlang 19+, and I had gotten it wrong. [...]  I should revisit type generation in gpb when targeting Erlang 17 and 18.

This should be fixed now in 4.17.6, which was just released, so I'll be close this issue (again, :) )

**Closed by tomas-abrahamsson** 2021-05-19 18:39 UTC

**Comment by paulo-ferraz-oliveira** [comment] 2021-05-19 19:56
Thanks much. I'll try it out.

**Comment by paulo-ferraz-oliveira** [comment] 2021-05-19 19:57
Should it work for target_erlang_version = 17?
